'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("CountryDTO"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class CountryDTO
    Inherits Global.System.Data.DataSet
    
    Private tableCountry As CountryDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Country")) Is Nothing) Then
                MyBase.Tables.Add(New CountryDataTable(ds.Tables("Country")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Country() As CountryDataTable
        Get
            Return Me.tableCountry
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As CountryDTO = CType(MyBase.Clone,CountryDTO)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("Country")) Is Nothing) Then
                MyBase.Tables.Add(New CountryDataTable(ds.Tables("Country")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableCountry = CType(MyBase.Tables("Country"),CountryDataTable)
        If (initTable = true) Then
            If (Not (Me.tableCountry) Is Nothing) Then
                Me.tableCountry.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "CountryDTO"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/CountryDTO.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableCountry = New CountryDataTable()
        MyBase.Tables.Add(Me.tableCountry)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Private Function ShouldSerializeCountry() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As CountryDTO = New CountryDTO()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Delegate Sub CountryRowChangeEventHandler(ByVal sender As Object, ByVal e As CountryRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class CountryDataTable
        Inherits Global.System.Data.TypedTableBase(Of CountryRow)
        
        Private columnCOUNTRY_ID As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_NAME As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_VISIBLE As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_AD As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_ADNAME As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_CSTMP As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_LUAD As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_LUADNAME As Global.System.Data.DataColumn
        
        Private columnCOUNTRY_LUSTMP As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "Country"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_VISIBLEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_VISIBLE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_ADColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_AD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_ADNAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_ADNAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_CSTMPColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_CSTMP
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_LUADColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_LUAD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_LUADNAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_LUADNAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property COUNTRY_LUSTMPColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNTRY_LUSTMP
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As CountryRow
            Get
                Return CType(Me.Rows(index),CountryRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CountryRowChanging As CountryRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CountryRowChanged As CountryRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CountryRowDeleting As CountryRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CountryRowDeleted As CountryRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Overloads Sub AddCountryRow(ByVal row As CountryRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Overloads Function AddCountryRow(ByVal COUNTRY_ID As String, ByVal COUNTRY_NAME As String, ByVal COUNTRY_VISIBLE As Decimal, ByVal COUNTRY_AD As String, ByVal COUNTRY_ADNAME As String, ByVal COUNTRY_CSTMP As Date, ByVal COUNTRY_LUAD As String, ByVal COUNTRY_LUADNAME As String, ByVal COUNTRY_LUSTMP As Date) As CountryRow
            Dim rowCountryRow As CountryRow = CType(Me.NewRow,CountryRow)
            Dim columnValuesArray() As Object = New Object() {COUNTRY_ID, COUNTRY_NAME, COUNTRY_VISIBLE, COUNTRY_AD, COUNTRY_ADNAME, COUNTRY_CSTMP, COUNTRY_LUAD, COUNTRY_LUADNAME, COUNTRY_LUSTMP}
            rowCountryRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowCountryRow)
            Return rowCountryRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Function FindByCOUNTRY_ID(ByVal COUNTRY_ID As String) As CountryRow
            Return CType(Me.Rows.Find(New Object() {COUNTRY_ID}),CountryRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As CountryDataTable = CType(MyBase.Clone,CountryDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New CountryDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnCOUNTRY_ID = MyBase.Columns("COUNTRY_ID")
            Me.columnCOUNTRY_NAME = MyBase.Columns("COUNTRY_NAME")
            Me.columnCOUNTRY_VISIBLE = MyBase.Columns("COUNTRY_VISIBLE")
            Me.columnCOUNTRY_AD = MyBase.Columns("COUNTRY_AD")
            Me.columnCOUNTRY_ADNAME = MyBase.Columns("COUNTRY_ADNAME")
            Me.columnCOUNTRY_CSTMP = MyBase.Columns("COUNTRY_CSTMP")
            Me.columnCOUNTRY_LUAD = MyBase.Columns("COUNTRY_LUAD")
            Me.columnCOUNTRY_LUADNAME = MyBase.Columns("COUNTRY_LUADNAME")
            Me.columnCOUNTRY_LUSTMP = MyBase.Columns("COUNTRY_LUSTMP")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitClass()
            Me.columnCOUNTRY_ID = New Global.System.Data.DataColumn("COUNTRY_ID", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_ID)
            Me.columnCOUNTRY_NAME = New Global.System.Data.DataColumn("COUNTRY_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_NAME)
            Me.columnCOUNTRY_VISIBLE = New Global.System.Data.DataColumn("COUNTRY_VISIBLE", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_VISIBLE)
            Me.columnCOUNTRY_AD = New Global.System.Data.DataColumn("COUNTRY_AD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_AD)
            Me.columnCOUNTRY_ADNAME = New Global.System.Data.DataColumn("COUNTRY_ADNAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_ADNAME)
            Me.columnCOUNTRY_CSTMP = New Global.System.Data.DataColumn("COUNTRY_CSTMP", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_CSTMP)
            Me.columnCOUNTRY_LUAD = New Global.System.Data.DataColumn("COUNTRY_LUAD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_LUAD)
            Me.columnCOUNTRY_LUADNAME = New Global.System.Data.DataColumn("COUNTRY_LUADNAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_LUADNAME)
            Me.columnCOUNTRY_LUSTMP = New Global.System.Data.DataColumn("COUNTRY_LUSTMP", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNTRY_LUSTMP)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnCOUNTRY_ID}, true))
            Me.columnCOUNTRY_ID.AllowDBNull = false
            Me.columnCOUNTRY_ID.Unique = true
            Me.columnCOUNTRY_ID.MaxLength = 40
            Me.columnCOUNTRY_NAME.AllowDBNull = false
            Me.columnCOUNTRY_NAME.MaxLength = 100
            Me.columnCOUNTRY_VISIBLE.AllowDBNull = false
            Me.columnCOUNTRY_AD.AllowDBNull = false
            Me.columnCOUNTRY_AD.MaxLength = 20
            Me.columnCOUNTRY_ADNAME.AllowDBNull = false
            Me.columnCOUNTRY_ADNAME.MaxLength = 50
            Me.columnCOUNTRY_CSTMP.AllowDBNull = false
            Me.columnCOUNTRY_LUAD.AllowDBNull = false
            Me.columnCOUNTRY_LUAD.MaxLength = 20
            Me.columnCOUNTRY_LUADNAME.AllowDBNull = false
            Me.columnCOUNTRY_LUADNAME.MaxLength = 50
            Me.columnCOUNTRY_LUSTMP.AllowDBNull = false
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Function NewCountryRow() As CountryRow
            Return CType(Me.NewRow,CountryRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New CountryRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(CountryRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.CountryRowChangedEvent) Is Nothing) Then
                RaiseEvent CountryRowChanged(Me, New CountryRowChangeEvent(CType(e.Row,CountryRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.CountryRowChangingEvent) Is Nothing) Then
                RaiseEvent CountryRowChanging(Me, New CountryRowChangeEvent(CType(e.Row,CountryRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.CountryRowDeletedEvent) Is Nothing) Then
                RaiseEvent CountryRowDeleted(Me, New CountryRowChangeEvent(CType(e.Row,CountryRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.CountryRowDeletingEvent) Is Nothing) Then
                RaiseEvent CountryRowDeleting(Me, New CountryRowChangeEvent(CType(e.Row,CountryRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub RemoveCountryRow(ByVal row As CountryRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As CountryDTO = New CountryDTO()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "CountryDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class CountryRow
        Inherits Global.System.Data.DataRow
        
        Private tableCountry As CountryDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableCountry = CType(Me.Table,CountryDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_ID() As String
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_IDColumn),String)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_NAME() As String
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_NAMEColumn),String)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_VISIBLE() As Decimal
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_VISIBLEColumn),Decimal)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_VISIBLEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_AD() As String
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_ADColumn),String)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_ADColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_ADNAME() As String
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_ADNAMEColumn),String)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_ADNAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_CSTMP() As Date
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_CSTMPColumn),Date)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_CSTMPColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_LUAD() As String
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_LUADColumn),String)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_LUADColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_LUADNAME() As String
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_LUADNAMEColumn),String)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_LUADNAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property COUNTRY_LUSTMP() As Date
            Get
                Return CType(Me(Me.tableCountry.COUNTRY_LUSTMPColumn),Date)
            End Get
            Set
                Me(Me.tableCountry.COUNTRY_LUSTMPColumn) = value
            End Set
        End Property
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Class CountryRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As CountryRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub New(ByVal row As CountryRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property Row() As CountryRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace CountryDTOTableAdapters
    
    '''<summary>
    '''Represents the connection and commands used to retrieve and save data.
    '''</summary>
    <Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
     Global.System.ComponentModel.ToolboxItem(true),  _
     Global.System.ComponentModel.DataObjectAttribute(true),  _
     Global.System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class CountryTableAdapter
        Inherits Global.System.ComponentModel.Component
        
        Private WithEvents _adapter As Global.System.Data.OracleClient.OracleDataAdapter
        
        Private _connection As Global.System.Data.OracleClient.OracleConnection
        
        Private _commandCollection() As Global.System.Data.OracleClient.OracleCommand
        
        Private _clearBeforeFill As Boolean
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.ClearBeforeFill = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private ReadOnly Property Adapter() As Global.System.Data.OracleClient.OracleDataAdapter
            Get
                If (Me._adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me._adapter
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Property Connection() As Global.System.Data.OracleClient.OracleConnection
            Get
                If (Me._connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me._connection
            End Get
            Set
                Me._connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),Global.System.Data.OracleClient.OracleCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected ReadOnly Property CommandCollection() As Global.System.Data.OracleClient.OracleCommand()
            Get
                If (Me._commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me._commandCollection
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me._clearBeforeFill
            End Get
            Set
                Me._clearBeforeFill = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitAdapter()
            Me._adapter = New Global.System.Data.OracleClient.OracleDataAdapter()
            Dim tableMapping As Global.System.Data.Common.DataTableMapping = New Global.System.Data.Common.DataTableMapping()
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "Country"
            tableMapping.ColumnMappings.Add("COUNTRY_ID", "COUNTRY_ID")
            tableMapping.ColumnMappings.Add("COUNTRY_NAME", "COUNTRY_NAME")
            tableMapping.ColumnMappings.Add("COUNTRY_VISIBLE", "COUNTRY_VISIBLE")
            tableMapping.ColumnMappings.Add("COUNTRY_AD", "COUNTRY_AD")
            tableMapping.ColumnMappings.Add("COUNTRY_ADNAME", "COUNTRY_ADNAME")
            tableMapping.ColumnMappings.Add("COUNTRY_CSTMP", "COUNTRY_CSTMP")
            tableMapping.ColumnMappings.Add("COUNTRY_LUAD", "COUNTRY_LUAD")
            tableMapping.ColumnMappings.Add("COUNTRY_LUADNAME", "COUNTRY_LUADNAME")
            tableMapping.ColumnMappings.Add("COUNTRY_LUSTMP", "COUNTRY_LUSTMP")
            Me._adapter.TableMappings.Add(tableMapping)
            Me._adapter.DeleteCommand = New Global.System.Data.OracleClient.OracleCommand()
            Me._adapter.DeleteCommand.Connection = Me.Connection
            Me._adapter.DeleteCommand.CommandText = "DELETE FROM ""CIPHERLAB"".""COUNTRY"" WHERE ((""COUNTRY_ID"" = :Original_COUNTRY_ID) AN"& _ 
                "D (""COUNTRY_NAME"" = :Original_COUNTRY_NAME) AND (""COUNTRY_VISIBLE"" = :Original_C"& _ 
                "OUNTRY_VISIBLE) AND (""COUNTRY_AD"" = :Original_COUNTRY_AD) AND (""COUNTRY_ADNAME"" "& _ 
                "= :Original_COUNTRY_ADNAME) AND (""COUNTRY_CSTMP"" = :Original_COUNTRY_CSTMP) AND "& _ 
                "(""COUNTRY_LUAD"" = :Original_COUNTRY_LUAD) AND (""COUNTRY_LUADNAME"" = :Original_CO"& _ 
                "UNTRY_LUADNAME) AND (""COUNTRY_LUSTMP"" = :Original_COUNTRY_LUSTMP))"
            Me._adapter.DeleteCommand.CommandType = Global.System.Data.CommandType.Text
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_ID", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ID", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_NAME", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_NAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_VISIBLE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_AD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_CSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUAD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.InsertCommand = New Global.System.Data.OracleClient.OracleCommand()
            Me._adapter.InsertCommand.Connection = Me.Connection
            Me._adapter.InsertCommand.CommandText = "INSERT INTO ""CIPHERLAB"".""COUNTRY"" (""COUNTRY_ID"", ""COUNTRY_NAME"", ""COUNTRY_VISIBLE"& _ 
                """, ""COUNTRY_AD"", ""COUNTRY_ADNAME"", ""COUNTRY_CSTMP"", ""COUNTRY_LUAD"", ""COUNTRY_LUA"& _ 
                "DNAME"", ""COUNTRY_LUSTMP"") VALUES (:COUNTRY_ID, :COUNTRY_NAME, :COUNTRY_VISIBLE, "& _ 
                ":COUNTRY_AD, :COUNTRY_ADNAME, :COUNTRY_CSTMP, :COUNTRY_LUAD, :COUNTRY_LUADNAME, "& _ 
                ":COUNTRY_LUSTMP)"
            Me._adapter.InsertCommand.CommandType = Global.System.Data.CommandType.Text
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_ID", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ID", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_NAME", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_NAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_VISIBLE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_AD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_CSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUAD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand = New Global.System.Data.OracleClient.OracleCommand()
            Me._adapter.UpdateCommand.Connection = Me.Connection
            Me._adapter.UpdateCommand.CommandText = "UPDATE ""CIPHERLAB"".""COUNTRY"" SET ""COUNTRY_ID"" = :COUNTRY_ID, ""COUNTRY_NAME"" = :CO"& _ 
                "UNTRY_NAME, ""COUNTRY_VISIBLE"" = :COUNTRY_VISIBLE, ""COUNTRY_AD"" = :COUNTRY_AD, ""C"& _ 
                "OUNTRY_ADNAME"" = :COUNTRY_ADNAME, ""COUNTRY_CSTMP"" = :COUNTRY_CSTMP, ""COUNTRY_LUA"& _ 
                "D"" = :COUNTRY_LUAD, ""COUNTRY_LUADNAME"" = :COUNTRY_LUADNAME, ""COUNTRY_LUSTMP"" = :"& _ 
                "COUNTRY_LUSTMP WHERE ((""COUNTRY_ID"" = :Original_COUNTRY_ID) AND (""COUNTRY_NAME"" "& _ 
                "= :Original_COUNTRY_NAME) AND (""COUNTRY_VISIBLE"" = :Original_COUNTRY_VISIBLE) AN"& _ 
                "D (""COUNTRY_AD"" = :Original_COUNTRY_AD) AND (""COUNTRY_ADNAME"" = :Original_COUNTR"& _ 
                "Y_ADNAME) AND (""COUNTRY_CSTMP"" = :Original_COUNTRY_CSTMP) AND (""COUNTRY_LUAD"" = "& _ 
                ":Original_COUNTRY_LUAD) AND (""COUNTRY_LUADNAME"" = :Original_COUNTRY_LUADNAME) AN"& _ 
                "D (""COUNTRY_LUSTMP"" = :Original_COUNTRY_LUSTMP))"
            Me._adapter.UpdateCommand.CommandType = Global.System.Data.CommandType.Text
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_ID", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ID", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_NAME", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_NAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_VISIBLE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_AD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_CSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUAD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("COUNTRY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_ID", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ID", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_NAME", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_NAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_VISIBLE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_AD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_ADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_CSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUAD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_COUNTRY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "COUNTRY_LUSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitConnection()
            Me._connection = New Global.System.Data.OracleClient.OracleConnection()
            Me._connection.ConnectionString = Global.DataService.My.MySettings.Default.ConnectionString
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitCommandCollection()
            Me._commandCollection = New Global.System.Data.OracleClient.OracleCommand(0) {}
            Me._commandCollection(0) = New Global.System.Data.OracleClient.OracleCommand()
            Me._commandCollection(0).Connection = Me.Connection
            Me._commandCollection(0).CommandText = "SELECT COUNTRY_ID, COUNTRY_NAME, COUNTRY_VISIBLE, COUNTRY_AD, COUNTRY_ADNAME, COU"& _ 
                "NTRY_CSTMP, COUNTRY_LUAD, COUNTRY_LUADNAME, COUNTRY_LUSTMP FROM CIPHERLAB.COUNTR"& _ 
                "Y"
            Me._commandCollection(0).CommandType = Global.System.Data.CommandType.Text
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As CountryDTO.CountryDataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.ClearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As CountryDTO.CountryDataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As CountryDTO.CountryDataTable = New CountryDTO.CountryDataTable()
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataTable As CountryDTO.CountryDataTable) As Integer
            Return Me.Adapter.Update(dataTable)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataSet As CountryDTO) As Integer
            Return Me.Adapter.Update(dataSet, "Country")
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRow As Global.System.Data.DataRow) As Integer
            Return Me.Adapter.Update(New Global.System.Data.DataRow() {dataRow})
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRows() As Global.System.Data.DataRow) As Integer
            Return Me.Adapter.Update(dataRows)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Overridable Function Delete(ByVal Original_COUNTRY_ID As String, ByVal Original_COUNTRY_NAME As String, ByVal Original_COUNTRY_VISIBLE As Decimal, ByVal Original_COUNTRY_AD As String, ByVal Original_COUNTRY_ADNAME As String, ByVal Original_COUNTRY_CSTMP As Date, ByVal Original_COUNTRY_LUAD As String, ByVal Original_COUNTRY_LUADNAME As String, ByVal Original_COUNTRY_LUSTMP As Date) As Integer
            If (Original_COUNTRY_ID Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_ID")
            Else
                Me.Adapter.DeleteCommand.Parameters(0).Value = CType(Original_COUNTRY_ID,String)
            End If
            If (Original_COUNTRY_NAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_NAME")
            Else
                Me.Adapter.DeleteCommand.Parameters(1).Value = CType(Original_COUNTRY_NAME,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(2).Value = CType(Original_COUNTRY_VISIBLE,Decimal)
            If (Original_COUNTRY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_AD")
            Else
                Me.Adapter.DeleteCommand.Parameters(3).Value = CType(Original_COUNTRY_AD,String)
            End If
            If (Original_COUNTRY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_ADNAME")
            Else
                Me.Adapter.DeleteCommand.Parameters(4).Value = CType(Original_COUNTRY_ADNAME,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(5).Value = CType(Original_COUNTRY_CSTMP,Date)
            If (Original_COUNTRY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_LUAD")
            Else
                Me.Adapter.DeleteCommand.Parameters(6).Value = CType(Original_COUNTRY_LUAD,String)
            End If
            If (Original_COUNTRY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_LUADNAME")
            Else
                Me.Adapter.DeleteCommand.Parameters(7).Value = CType(Original_COUNTRY_LUADNAME,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(8).Value = CType(Original_COUNTRY_LUSTMP,Date)
            Dim previousConnectionState As Global.System.Data.ConnectionState = Me.Adapter.DeleteCommand.Connection.State
            If ((Me.Adapter.DeleteCommand.Connection.State And Global.System.Data.ConnectionState.Open)  _
                        <> Global.System.Data.ConnectionState.Open) Then
                Me.Adapter.DeleteCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.DeleteCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = Global.System.Data.ConnectionState.Closed) Then
                    Me.Adapter.DeleteCommand.Connection.Close
                End If
            End Try
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Overloads Overridable Function Insert(ByVal COUNTRY_ID As String, ByVal COUNTRY_NAME As String, ByVal COUNTRY_VISIBLE As Decimal, ByVal COUNTRY_AD As String, ByVal COUNTRY_ADNAME As String, ByVal COUNTRY_CSTMP As Date, ByVal COUNTRY_LUAD As String, ByVal COUNTRY_LUADNAME As String, ByVal COUNTRY_LUSTMP As Date) As Integer
            If (COUNTRY_ID Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_ID")
            Else
                Me.Adapter.InsertCommand.Parameters(0).Value = CType(COUNTRY_ID,String)
            End If
            If (COUNTRY_NAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_NAME")
            Else
                Me.Adapter.InsertCommand.Parameters(1).Value = CType(COUNTRY_NAME,String)
            End If
            Me.Adapter.InsertCommand.Parameters(2).Value = CType(COUNTRY_VISIBLE,Decimal)
            If (COUNTRY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_AD")
            Else
                Me.Adapter.InsertCommand.Parameters(3).Value = CType(COUNTRY_AD,String)
            End If
            If (COUNTRY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_ADNAME")
            Else
                Me.Adapter.InsertCommand.Parameters(4).Value = CType(COUNTRY_ADNAME,String)
            End If
            Me.Adapter.InsertCommand.Parameters(5).Value = CType(COUNTRY_CSTMP,Date)
            If (COUNTRY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_LUAD")
            Else
                Me.Adapter.InsertCommand.Parameters(6).Value = CType(COUNTRY_LUAD,String)
            End If
            If (COUNTRY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_LUADNAME")
            Else
                Me.Adapter.InsertCommand.Parameters(7).Value = CType(COUNTRY_LUADNAME,String)
            End If
            Me.Adapter.InsertCommand.Parameters(8).Value = CType(COUNTRY_LUSTMP,Date)
            Dim previousConnectionState As Global.System.Data.ConnectionState = Me.Adapter.InsertCommand.Connection.State
            If ((Me.Adapter.InsertCommand.Connection.State And Global.System.Data.ConnectionState.Open)  _
                        <> Global.System.Data.ConnectionState.Open) Then
                Me.Adapter.InsertCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.InsertCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = Global.System.Data.ConnectionState.Closed) Then
                    Me.Adapter.InsertCommand.Connection.Close
                End If
            End Try
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Overridable Function Update( _
                    ByVal COUNTRY_ID As String,  _
                    ByVal COUNTRY_NAME As String,  _
                    ByVal COUNTRY_VISIBLE As Decimal,  _
                    ByVal COUNTRY_AD As String,  _
                    ByVal COUNTRY_ADNAME As String,  _
                    ByVal COUNTRY_CSTMP As Date,  _
                    ByVal COUNTRY_LUAD As String,  _
                    ByVal COUNTRY_LUADNAME As String,  _
                    ByVal COUNTRY_LUSTMP As Date,  _
                    ByVal Original_COUNTRY_ID As String,  _
                    ByVal Original_COUNTRY_NAME As String,  _
                    ByVal Original_COUNTRY_VISIBLE As Decimal,  _
                    ByVal Original_COUNTRY_AD As String,  _
                    ByVal Original_COUNTRY_ADNAME As String,  _
                    ByVal Original_COUNTRY_CSTMP As Date,  _
                    ByVal Original_COUNTRY_LUAD As String,  _
                    ByVal Original_COUNTRY_LUADNAME As String,  _
                    ByVal Original_COUNTRY_LUSTMP As Date) As Integer
            If (COUNTRY_ID Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_ID")
            Else
                Me.Adapter.UpdateCommand.Parameters(0).Value = CType(COUNTRY_ID,String)
            End If
            If (COUNTRY_NAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_NAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(1).Value = CType(COUNTRY_NAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(2).Value = CType(COUNTRY_VISIBLE,Decimal)
            If (COUNTRY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_AD")
            Else
                Me.Adapter.UpdateCommand.Parameters(3).Value = CType(COUNTRY_AD,String)
            End If
            If (COUNTRY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_ADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(4).Value = CType(COUNTRY_ADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(5).Value = CType(COUNTRY_CSTMP,Date)
            If (COUNTRY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_LUAD")
            Else
                Me.Adapter.UpdateCommand.Parameters(6).Value = CType(COUNTRY_LUAD,String)
            End If
            If (COUNTRY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("COUNTRY_LUADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(7).Value = CType(COUNTRY_LUADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(8).Value = CType(COUNTRY_LUSTMP,Date)
            If (Original_COUNTRY_ID Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_ID")
            Else
                Me.Adapter.UpdateCommand.Parameters(9).Value = CType(Original_COUNTRY_ID,String)
            End If
            If (Original_COUNTRY_NAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_NAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(10).Value = CType(Original_COUNTRY_NAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(11).Value = CType(Original_COUNTRY_VISIBLE,Decimal)
            If (Original_COUNTRY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_AD")
            Else
                Me.Adapter.UpdateCommand.Parameters(12).Value = CType(Original_COUNTRY_AD,String)
            End If
            If (Original_COUNTRY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_ADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(13).Value = CType(Original_COUNTRY_ADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(14).Value = CType(Original_COUNTRY_CSTMP,Date)
            If (Original_COUNTRY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_LUAD")
            Else
                Me.Adapter.UpdateCommand.Parameters(15).Value = CType(Original_COUNTRY_LUAD,String)
            End If
            If (Original_COUNTRY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_COUNTRY_LUADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(16).Value = CType(Original_COUNTRY_LUADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(17).Value = CType(Original_COUNTRY_LUSTMP,Date)
            Dim previousConnectionState As Global.System.Data.ConnectionState = Me.Adapter.UpdateCommand.Connection.State
            If ((Me.Adapter.UpdateCommand.Connection.State And Global.System.Data.ConnectionState.Open)  _
                        <> Global.System.Data.ConnectionState.Open) Then
                Me.Adapter.UpdateCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.UpdateCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = Global.System.Data.ConnectionState.Closed) Then
                    Me.Adapter.UpdateCommand.Connection.Close
                End If
            End Try
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Overridable Function Update( _
                    ByVal COUNTRY_NAME As String,  _
                    ByVal COUNTRY_VISIBLE As Decimal,  _
                    ByVal COUNTRY_AD As String,  _
                    ByVal COUNTRY_ADNAME As String,  _
                    ByVal COUNTRY_CSTMP As Date,  _
                    ByVal COUNTRY_LUAD As String,  _
                    ByVal COUNTRY_LUADNAME As String,  _
                    ByVal COUNTRY_LUSTMP As Date,  _
                    ByVal Original_COUNTRY_ID As String,  _
                    ByVal Original_COUNTRY_NAME As String,  _
                    ByVal Original_COUNTRY_VISIBLE As Decimal,  _
                    ByVal Original_COUNTRY_AD As String,  _
                    ByVal Original_COUNTRY_ADNAME As String,  _
                    ByVal Original_COUNTRY_CSTMP As Date,  _
                    ByVal Original_COUNTRY_LUAD As String,  _
                    ByVal Original_COUNTRY_LUADNAME As String,  _
                    ByVal Original_COUNTRY_LUSTMP As Date) As Integer
            Return Me.Update(Original_COUNTRY_ID, COUNTRY_NAME, COUNTRY_VISIBLE, COUNTRY_AD, COUNTRY_ADNAME, COUNTRY_CSTMP, COUNTRY_LUAD, COUNTRY_LUADNAME, COUNTRY_LUSTMP, Original_COUNTRY_ID, Original_COUNTRY_NAME, Original_COUNTRY_VISIBLE, Original_COUNTRY_AD, Original_COUNTRY_ADNAME, Original_COUNTRY_CSTMP, Original_COUNTRY_LUAD, Original_COUNTRY_LUADNAME, Original_COUNTRY_LUSTMP)
        End Function
    End Class
End Namespace
