'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("CurrencyDTO"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class CurrencyDTO
    Inherits Global.System.Data.DataSet
    
    Private tableCurrency As CurrencyDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Currency")) Is Nothing) Then
                MyBase.Tables.Add(New CurrencyDataTable(ds.Tables("Currency")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Currency() As CurrencyDataTable
        Get
            Return Me.tableCurrency
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As CurrencyDTO = CType(MyBase.Clone,CurrencyDTO)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("Currency")) Is Nothing) Then
                MyBase.Tables.Add(New CurrencyDataTable(ds.Tables("Currency")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableCurrency = CType(MyBase.Tables("Currency"),CurrencyDataTable)
        If (initTable = true) Then
            If (Not (Me.tableCurrency) Is Nothing) Then
                Me.tableCurrency.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "CurrencyDTO"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/CurrencyDTO.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableCurrency = New CurrencyDataTable()
        MyBase.Tables.Add(Me.tableCurrency)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Private Function ShouldSerializeCurrency() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As CurrencyDTO = New CurrencyDTO()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Delegate Sub CurrencyRowChangeEventHandler(ByVal sender As Object, ByVal e As CurrencyRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class CurrencyDataTable
        Inherits Global.System.Data.TypedTableBase(Of CurrencyRow)
        
        Private columnCURRENCY_CODE As Global.System.Data.DataColumn
        
        Private columnCURRENCY_RATE As Global.System.Data.DataColumn
        
        Private columnCURRENCY_VISIBLE As Global.System.Data.DataColumn
        
        Private columnCURRENCY_SYMBOL As Global.System.Data.DataColumn
        
        Private columnCURRENCY_AD As Global.System.Data.DataColumn
        
        Private columnCURRENCY_ADNAME As Global.System.Data.DataColumn
        
        Private columnCURRENCY_CSTMP As Global.System.Data.DataColumn
        
        Private columnCURRENCY_LUAD As Global.System.Data.DataColumn
        
        Private columnCURRENCY_LUADNAME As Global.System.Data.DataColumn
        
        Private columnCURRENCY_LUSTMP As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "Currency"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_CODEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_CODE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_RATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_RATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_VISIBLEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_VISIBLE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_SYMBOLColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_SYMBOL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_ADColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_AD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_ADNAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_ADNAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_CSTMPColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_CSTMP
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_LUADColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_LUAD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_LUADNAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_LUADNAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property CURRENCY_LUSTMPColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCURRENCY_LUSTMP
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As CurrencyRow
            Get
                Return CType(Me.Rows(index),CurrencyRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CurrencyRowChanging As CurrencyRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CurrencyRowChanged As CurrencyRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CurrencyRowDeleting As CurrencyRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Event CurrencyRowDeleted As CurrencyRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Overloads Sub AddCurrencyRow(ByVal row As CurrencyRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Overloads Function AddCurrencyRow(ByVal CURRENCY_CODE As String, ByVal CURRENCY_RATE As Decimal, ByVal CURRENCY_VISIBLE As Decimal, ByVal CURRENCY_SYMBOL As String, ByVal CURRENCY_AD As String, ByVal CURRENCY_ADNAME As String, ByVal CURRENCY_CSTMP As Date, ByVal CURRENCY_LUAD As String, ByVal CURRENCY_LUADNAME As String, ByVal CURRENCY_LUSTMP As Date) As CurrencyRow
            Dim rowCurrencyRow As CurrencyRow = CType(Me.NewRow,CurrencyRow)
            Dim columnValuesArray() As Object = New Object() {CURRENCY_CODE, CURRENCY_RATE, CURRENCY_VISIBLE, CURRENCY_SYMBOL, CURRENCY_AD, CURRENCY_ADNAME, CURRENCY_CSTMP, CURRENCY_LUAD, CURRENCY_LUADNAME, CURRENCY_LUSTMP}
            rowCurrencyRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowCurrencyRow)
            Return rowCurrencyRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Function FindByCURRENCY_CODE(ByVal CURRENCY_CODE As String) As CurrencyRow
            Return CType(Me.Rows.Find(New Object() {CURRENCY_CODE}),CurrencyRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As CurrencyDataTable = CType(MyBase.Clone,CurrencyDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New CurrencyDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnCURRENCY_CODE = MyBase.Columns("CURRENCY_CODE")
            Me.columnCURRENCY_RATE = MyBase.Columns("CURRENCY_RATE")
            Me.columnCURRENCY_VISIBLE = MyBase.Columns("CURRENCY_VISIBLE")
            Me.columnCURRENCY_SYMBOL = MyBase.Columns("CURRENCY_SYMBOL")
            Me.columnCURRENCY_AD = MyBase.Columns("CURRENCY_AD")
            Me.columnCURRENCY_ADNAME = MyBase.Columns("CURRENCY_ADNAME")
            Me.columnCURRENCY_CSTMP = MyBase.Columns("CURRENCY_CSTMP")
            Me.columnCURRENCY_LUAD = MyBase.Columns("CURRENCY_LUAD")
            Me.columnCURRENCY_LUADNAME = MyBase.Columns("CURRENCY_LUADNAME")
            Me.columnCURRENCY_LUSTMP = MyBase.Columns("CURRENCY_LUSTMP")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitClass()
            Me.columnCURRENCY_CODE = New Global.System.Data.DataColumn("CURRENCY_CODE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_CODE)
            Me.columnCURRENCY_RATE = New Global.System.Data.DataColumn("CURRENCY_RATE", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_RATE)
            Me.columnCURRENCY_VISIBLE = New Global.System.Data.DataColumn("CURRENCY_VISIBLE", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_VISIBLE)
            Me.columnCURRENCY_SYMBOL = New Global.System.Data.DataColumn("CURRENCY_SYMBOL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_SYMBOL)
            Me.columnCURRENCY_AD = New Global.System.Data.DataColumn("CURRENCY_AD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_AD)
            Me.columnCURRENCY_ADNAME = New Global.System.Data.DataColumn("CURRENCY_ADNAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_ADNAME)
            Me.columnCURRENCY_CSTMP = New Global.System.Data.DataColumn("CURRENCY_CSTMP", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_CSTMP)
            Me.columnCURRENCY_LUAD = New Global.System.Data.DataColumn("CURRENCY_LUAD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_LUAD)
            Me.columnCURRENCY_LUADNAME = New Global.System.Data.DataColumn("CURRENCY_LUADNAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_LUADNAME)
            Me.columnCURRENCY_LUSTMP = New Global.System.Data.DataColumn("CURRENCY_LUSTMP", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCURRENCY_LUSTMP)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnCURRENCY_CODE}, true))
            Me.columnCURRENCY_CODE.AllowDBNull = false
            Me.columnCURRENCY_CODE.Unique = true
            Me.columnCURRENCY_CODE.MaxLength = 40
            Me.columnCURRENCY_RATE.AllowDBNull = false
            Me.columnCURRENCY_VISIBLE.AllowDBNull = false
            Me.columnCURRENCY_SYMBOL.MaxLength = 20
            Me.columnCURRENCY_AD.AllowDBNull = false
            Me.columnCURRENCY_AD.MaxLength = 20
            Me.columnCURRENCY_ADNAME.AllowDBNull = false
            Me.columnCURRENCY_ADNAME.MaxLength = 50
            Me.columnCURRENCY_CSTMP.AllowDBNull = false
            Me.columnCURRENCY_LUAD.AllowDBNull = false
            Me.columnCURRENCY_LUAD.MaxLength = 20
            Me.columnCURRENCY_LUADNAME.AllowDBNull = false
            Me.columnCURRENCY_LUADNAME.MaxLength = 50
            Me.columnCURRENCY_LUSTMP.AllowDBNull = false
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Function NewCurrencyRow() As CurrencyRow
            Return CType(Me.NewRow,CurrencyRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New CurrencyRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(CurrencyRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.CurrencyRowChangedEvent) Is Nothing) Then
                RaiseEvent CurrencyRowChanged(Me, New CurrencyRowChangeEvent(CType(e.Row,CurrencyRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.CurrencyRowChangingEvent) Is Nothing) Then
                RaiseEvent CurrencyRowChanging(Me, New CurrencyRowChangeEvent(CType(e.Row,CurrencyRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.CurrencyRowDeletedEvent) Is Nothing) Then
                RaiseEvent CurrencyRowDeleted(Me, New CurrencyRowChangeEvent(CType(e.Row,CurrencyRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.CurrencyRowDeletingEvent) Is Nothing) Then
                RaiseEvent CurrencyRowDeleting(Me, New CurrencyRowChangeEvent(CType(e.Row,CurrencyRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub RemoveCurrencyRow(ByVal row As CurrencyRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As CurrencyDTO = New CurrencyDTO()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "CurrencyDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class CurrencyRow
        Inherits Global.System.Data.DataRow
        
        Private tableCurrency As CurrencyDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableCurrency = CType(Me.Table,CurrencyDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_CODE() As String
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_CODEColumn),String)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_CODEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_RATE() As Decimal
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_RATEColumn),Decimal)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_RATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_VISIBLE() As Decimal
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_VISIBLEColumn),Decimal)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_VISIBLEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_SYMBOL() As String
            Get
                Try 
                    Return CType(Me(Me.tableCurrency.CURRENCY_SYMBOLColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("資料表 'Currency' 中資料行 'CURRENCY_SYMBOL' 的值是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_SYMBOLColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_AD() As String
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_ADColumn),String)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_ADColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_ADNAME() As String
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_ADNAMEColumn),String)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_ADNAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_CSTMP() As Date
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_CSTMPColumn),Date)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_CSTMPColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_LUAD() As String
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_LUADColumn),String)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_LUADColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_LUADNAME() As String
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_LUADNAMEColumn),String)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_LUADNAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property CURRENCY_LUSTMP() As Date
            Get
                Return CType(Me(Me.tableCurrency.CURRENCY_LUSTMPColumn),Date)
            End Get
            Set
                Me(Me.tableCurrency.CURRENCY_LUSTMPColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Function IsCURRENCY_SYMBOLNull() As Boolean
            Return Me.IsNull(Me.tableCurrency.CURRENCY_SYMBOLColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub SetCURRENCY_SYMBOLNull()
            Me(Me.tableCurrency.CURRENCY_SYMBOLColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
    Public Class CurrencyRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As CurrencyRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub New(ByVal row As CurrencyRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property Row() As CurrencyRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace CurrencyDTOTableAdapters
    
    '''<summary>
    '''Represents the connection and commands used to retrieve and save data.
    '''</summary>
    <Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
     Global.System.ComponentModel.ToolboxItem(true),  _
     Global.System.ComponentModel.DataObjectAttribute(true),  _
     Global.System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class CurrencyTableAdapter
        Inherits Global.System.ComponentModel.Component
        
        Private WithEvents _adapter As Global.System.Data.OracleClient.OracleDataAdapter
        
        Private _connection As Global.System.Data.OracleClient.OracleConnection
        
        Private _commandCollection() As Global.System.Data.OracleClient.OracleCommand
        
        Private _clearBeforeFill As Boolean
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.ClearBeforeFill = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private ReadOnly Property Adapter() As Global.System.Data.OracleClient.OracleDataAdapter
            Get
                If (Me._adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me._adapter
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Friend Property Connection() As Global.System.Data.OracleClient.OracleConnection
            Get
                If (Me._connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me._connection
            End Get
            Set
                Me._connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),Global.System.Data.OracleClient.OracleCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Protected ReadOnly Property CommandCollection() As Global.System.Data.OracleClient.OracleCommand()
            Get
                If (Me._commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me._commandCollection
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me._clearBeforeFill
            End Get
            Set
                Me._clearBeforeFill = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitAdapter()
            Me._adapter = New Global.System.Data.OracleClient.OracleDataAdapter()
            Dim tableMapping As Global.System.Data.Common.DataTableMapping = New Global.System.Data.Common.DataTableMapping()
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "Currency"
            tableMapping.ColumnMappings.Add("CURRENCY_CODE", "CURRENCY_CODE")
            tableMapping.ColumnMappings.Add("CURRENCY_RATE", "CURRENCY_RATE")
            tableMapping.ColumnMappings.Add("CURRENCY_VISIBLE", "CURRENCY_VISIBLE")
            tableMapping.ColumnMappings.Add("CURRENCY_SYMBOL", "CURRENCY_SYMBOL")
            tableMapping.ColumnMappings.Add("CURRENCY_AD", "CURRENCY_AD")
            tableMapping.ColumnMappings.Add("CURRENCY_ADNAME", "CURRENCY_ADNAME")
            tableMapping.ColumnMappings.Add("CURRENCY_CSTMP", "CURRENCY_CSTMP")
            tableMapping.ColumnMappings.Add("CURRENCY_LUAD", "CURRENCY_LUAD")
            tableMapping.ColumnMappings.Add("CURRENCY_LUADNAME", "CURRENCY_LUADNAME")
            tableMapping.ColumnMappings.Add("CURRENCY_LUSTMP", "CURRENCY_LUSTMP")
            Me._adapter.TableMappings.Add(tableMapping)
            Me._adapter.DeleteCommand = New Global.System.Data.OracleClient.OracleCommand()
            Me._adapter.DeleteCommand.Connection = Me.Connection
            Me._adapter.DeleteCommand.CommandText = "DELETE FROM ""CIPHERLAB"".""CURRENCY"" WHERE ((""CURRENCY_CODE"" = :Original_CURRENCY_C"& _ 
                "ODE) AND (""CURRENCY_RATE"" = :Original_CURRENCY_RATE) AND (""CURRENCY_VISIBLE"" = :"& _ 
                "Original_CURRENCY_VISIBLE) AND ((:IsNull_CURRENCY_SYMBOL = 1 AND ""CURRENCY_SYMBO"& _ 
                "L"" IS NULL) OR (""CURRENCY_SYMBOL"" = :Original_CURRENCY_SYMBOL)) AND (""CURRENCY_A"& _ 
                "D"" = :Original_CURRENCY_AD) AND (""CURRENCY_ADNAME"" = :Original_CURRENCY_ADNAME) "& _ 
                "AND (""CURRENCY_CSTMP"" = :Original_CURRENCY_CSTMP) AND (""CURRENCY_LUAD"" = :Origin"& _ 
                "al_CURRENCY_LUAD) AND (""CURRENCY_LUADNAME"" = :Original_CURRENCY_LUADNAME) AND ("""& _ 
                "CURRENCY_LUSTMP"" = :Original_CURRENCY_LUSTMP))"
            Me._adapter.DeleteCommand.CommandType = Global.System.Data.CommandType.Text
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_CODE", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CODE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_RATE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_RATE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_VISIBLE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("IsNull_CURRENCY_SYMBOL", Global.System.Data.OracleClient.OracleType.Int32, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_SYMBOL", Global.System.Data.DataRowVersion.Original, true, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_SYMBOL", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_SYMBOL", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_AD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_ADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUAD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.DeleteCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.InsertCommand = New Global.System.Data.OracleClient.OracleCommand()
            Me._adapter.InsertCommand.Connection = Me.Connection
            Me._adapter.InsertCommand.CommandText = "INSERT INTO ""CIPHERLAB"".""CURRENCY"" (""CURRENCY_CODE"", ""CURRENCY_RATE"", ""CURRENCY_V"& _ 
                "ISIBLE"", ""CURRENCY_SYMBOL"", ""CURRENCY_AD"", ""CURRENCY_ADNAME"", ""CURRENCY_CSTMP"", "& _ 
                """CURRENCY_LUAD"", ""CURRENCY_LUADNAME"", ""CURRENCY_LUSTMP"") VALUES (:CURRENCY_CODE,"& _ 
                " :CURRENCY_RATE, :CURRENCY_VISIBLE, :CURRENCY_SYMBOL, :CURRENCY_AD, :CURRENCY_AD"& _ 
                "NAME, :CURRENCY_CSTMP, :CURRENCY_LUAD, :CURRENCY_LUADNAME, :CURRENCY_LUSTMP)"
            Me._adapter.InsertCommand.CommandType = Global.System.Data.CommandType.Text
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_CODE", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CODE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_RATE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_RATE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_VISIBLE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_SYMBOL", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_SYMBOL", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_AD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_ADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUAD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.InsertCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand = New Global.System.Data.OracleClient.OracleCommand()
            Me._adapter.UpdateCommand.Connection = Me.Connection
            Me._adapter.UpdateCommand.CommandText = "UPDATE ""CIPHERLAB"".""CURRENCY"" SET ""CURRENCY_CODE"" = :CURRENCY_CODE, ""CURRENCY_RAT"& _ 
                "E"" = :CURRENCY_RATE, ""CURRENCY_VISIBLE"" = :CURRENCY_VISIBLE, ""CURRENCY_SYMBOL"" ="& _ 
                " :CURRENCY_SYMBOL, ""CURRENCY_AD"" = :CURRENCY_AD, ""CURRENCY_ADNAME"" = :CURRENCY_A"& _ 
                "DNAME, ""CURRENCY_CSTMP"" = :CURRENCY_CSTMP, ""CURRENCY_LUAD"" = :CURRENCY_LUAD, ""CU"& _ 
                "RRENCY_LUADNAME"" = :CURRENCY_LUADNAME, ""CURRENCY_LUSTMP"" = :CURRENCY_LUSTMP WHER"& _ 
                "E ((""CURRENCY_CODE"" = :Original_CURRENCY_CODE) AND (""CURRENCY_RATE"" = :Original_"& _ 
                "CURRENCY_RATE) AND (""CURRENCY_VISIBLE"" = :Original_CURRENCY_VISIBLE) AND ((:IsNu"& _ 
                "ll_CURRENCY_SYMBOL = 1 AND ""CURRENCY_SYMBOL"" IS NULL) OR (""CURRENCY_SYMBOL"" = :O"& _ 
                "riginal_CURRENCY_SYMBOL)) AND (""CURRENCY_AD"" = :Original_CURRENCY_AD) AND (""CURR"& _ 
                "ENCY_ADNAME"" = :Original_CURRENCY_ADNAME) AND (""CURRENCY_CSTMP"" = :Original_CURR"& _ 
                "ENCY_CSTMP) AND (""CURRENCY_LUAD"" = :Original_CURRENCY_LUAD) AND (""CURRENCY_LUADN"& _ 
                "AME"" = :Original_CURRENCY_LUADNAME) AND (""CURRENCY_LUSTMP"" = :Original_CURRENCY_"& _ 
                "LUSTMP))"
            Me._adapter.UpdateCommand.CommandType = Global.System.Data.CommandType.Text
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_CODE", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CODE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_RATE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_RATE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_VISIBLE", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_SYMBOL", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_SYMBOL", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_AD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_ADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUAD", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUADNAME", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("CURRENCY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUSTMP", Global.System.Data.DataRowVersion.Current, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_CODE", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CODE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_RATE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_RATE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_VISIBLE", Global.System.Data.OracleClient.OracleType.Number, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_VISIBLE", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("IsNull_CURRENCY_SYMBOL", Global.System.Data.OracleClient.OracleType.Int32, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_SYMBOL", Global.System.Data.DataRowVersion.Original, true, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_SYMBOL", Global.System.Data.OracleClient.OracleType.VarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_SYMBOL", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_AD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_AD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_ADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_ADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_CSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_CSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_LUAD", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUAD", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_LUADNAME", Global.System.Data.OracleClient.OracleType.NVarChar, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUADNAME", Global.System.Data.DataRowVersion.Original, false, Nothing))
            Me._adapter.UpdateCommand.Parameters.Add(New Global.System.Data.OracleClient.OracleParameter("Original_CURRENCY_LUSTMP", Global.System.Data.OracleClient.OracleType.DateTime, 0, Global.System.Data.ParameterDirection.Input, "CURRENCY_LUSTMP", Global.System.Data.DataRowVersion.Original, false, Nothing))
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitConnection()
            Me._connection = New Global.System.Data.OracleClient.OracleConnection()
            Me._connection.ConnectionString = Global.DataService.My.MySettings.Default.ConnectionString
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")>  _
        Private Sub InitCommandCollection()
            Me._commandCollection = New Global.System.Data.OracleClient.OracleCommand(0) {}
            Me._commandCollection(0) = New Global.System.Data.OracleClient.OracleCommand()
            Me._commandCollection(0).Connection = Me.Connection
            Me._commandCollection(0).CommandText = "SELECT CURRENCY_CODE, CURRENCY_RATE, CURRENCY_VISIBLE, CURRENCY_SYMBOL, CURRENCY_"& _ 
                "AD, CURRENCY_ADNAME, CURRENCY_CSTMP, CURRENCY_LUAD, CURRENCY_LUADNAME, CURRENCY_"& _ 
                "LUSTMP FROM CIPHERLAB.CURRENCY"
            Me._commandCollection(0).CommandType = Global.System.Data.CommandType.Text
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As CurrencyDTO.CurrencyDataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.ClearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As CurrencyDTO.CurrencyDataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As CurrencyDTO.CurrencyDataTable = New CurrencyDTO.CurrencyDataTable()
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataTable As CurrencyDTO.CurrencyDataTable) As Integer
            Return Me.Adapter.Update(dataTable)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataSet As CurrencyDTO) As Integer
            Return Me.Adapter.Update(dataSet, "Currency")
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRow As Global.System.Data.DataRow) As Integer
            Return Me.Adapter.Update(New Global.System.Data.DataRow() {dataRow})
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
        Public Overloads Overridable Function Update(ByVal dataRows() As Global.System.Data.DataRow) As Integer
            Return Me.Adapter.Update(dataRows)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Overridable Function Delete(ByVal Original_CURRENCY_CODE As String, ByVal Original_CURRENCY_RATE As Decimal, ByVal Original_CURRENCY_VISIBLE As Decimal, ByVal Original_CURRENCY_SYMBOL As String, ByVal Original_CURRENCY_AD As String, ByVal Original_CURRENCY_ADNAME As String, ByVal Original_CURRENCY_CSTMP As Date, ByVal Original_CURRENCY_LUAD As String, ByVal Original_CURRENCY_LUADNAME As String, ByVal Original_CURRENCY_LUSTMP As Date) As Integer
            If (Original_CURRENCY_CODE Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_CODE")
            Else
                Me.Adapter.DeleteCommand.Parameters(0).Value = CType(Original_CURRENCY_CODE,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(1).Value = CType(Original_CURRENCY_RATE,Decimal)
            Me.Adapter.DeleteCommand.Parameters(2).Value = CType(Original_CURRENCY_VISIBLE,Decimal)
            If (Original_CURRENCY_SYMBOL Is Nothing) Then
                Me.Adapter.DeleteCommand.Parameters(3).Value = CType(1,Object)
                Me.Adapter.DeleteCommand.Parameters(4).Value = Global.System.DBNull.Value
            Else
                Me.Adapter.DeleteCommand.Parameters(3).Value = CType(0,Object)
                Me.Adapter.DeleteCommand.Parameters(4).Value = CType(Original_CURRENCY_SYMBOL,String)
            End If
            If (Original_CURRENCY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_AD")
            Else
                Me.Adapter.DeleteCommand.Parameters(5).Value = CType(Original_CURRENCY_AD,String)
            End If
            If (Original_CURRENCY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_ADNAME")
            Else
                Me.Adapter.DeleteCommand.Parameters(6).Value = CType(Original_CURRENCY_ADNAME,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(7).Value = CType(Original_CURRENCY_CSTMP,Date)
            If (Original_CURRENCY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_LUAD")
            Else
                Me.Adapter.DeleteCommand.Parameters(8).Value = CType(Original_CURRENCY_LUAD,String)
            End If
            If (Original_CURRENCY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_LUADNAME")
            Else
                Me.Adapter.DeleteCommand.Parameters(9).Value = CType(Original_CURRENCY_LUADNAME,String)
            End If
            Me.Adapter.DeleteCommand.Parameters(10).Value = CType(Original_CURRENCY_LUSTMP,Date)
            Dim previousConnectionState As Global.System.Data.ConnectionState = Me.Adapter.DeleteCommand.Connection.State
            If ((Me.Adapter.DeleteCommand.Connection.State And Global.System.Data.ConnectionState.Open)  _
                        <> Global.System.Data.ConnectionState.Open) Then
                Me.Adapter.DeleteCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.DeleteCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = Global.System.Data.ConnectionState.Closed) Then
                    Me.Adapter.DeleteCommand.Connection.Close
                End If
            End Try
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Overloads Overridable Function Insert(ByVal CURRENCY_CODE As String, ByVal CURRENCY_RATE As Decimal, ByVal CURRENCY_VISIBLE As Decimal, ByVal CURRENCY_SYMBOL As String, ByVal CURRENCY_AD As String, ByVal CURRENCY_ADNAME As String, ByVal CURRENCY_CSTMP As Date, ByVal CURRENCY_LUAD As String, ByVal CURRENCY_LUADNAME As String, ByVal CURRENCY_LUSTMP As Date) As Integer
            If (CURRENCY_CODE Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_CODE")
            Else
                Me.Adapter.InsertCommand.Parameters(0).Value = CType(CURRENCY_CODE,String)
            End If
            Me.Adapter.InsertCommand.Parameters(1).Value = CType(CURRENCY_RATE,Decimal)
            Me.Adapter.InsertCommand.Parameters(2).Value = CType(CURRENCY_VISIBLE,Decimal)
            If (CURRENCY_SYMBOL Is Nothing) Then
                Me.Adapter.InsertCommand.Parameters(3).Value = Global.System.DBNull.Value
            Else
                Me.Adapter.InsertCommand.Parameters(3).Value = CType(CURRENCY_SYMBOL,String)
            End If
            If (CURRENCY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_AD")
            Else
                Me.Adapter.InsertCommand.Parameters(4).Value = CType(CURRENCY_AD,String)
            End If
            If (CURRENCY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_ADNAME")
            Else
                Me.Adapter.InsertCommand.Parameters(5).Value = CType(CURRENCY_ADNAME,String)
            End If
            Me.Adapter.InsertCommand.Parameters(6).Value = CType(CURRENCY_CSTMP,Date)
            If (CURRENCY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_LUAD")
            Else
                Me.Adapter.InsertCommand.Parameters(7).Value = CType(CURRENCY_LUAD,String)
            End If
            If (CURRENCY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_LUADNAME")
            Else
                Me.Adapter.InsertCommand.Parameters(8).Value = CType(CURRENCY_LUADNAME,String)
            End If
            Me.Adapter.InsertCommand.Parameters(9).Value = CType(CURRENCY_LUSTMP,Date)
            Dim previousConnectionState As Global.System.Data.ConnectionState = Me.Adapter.InsertCommand.Connection.State
            If ((Me.Adapter.InsertCommand.Connection.State And Global.System.Data.ConnectionState.Open)  _
                        <> Global.System.Data.ConnectionState.Open) Then
                Me.Adapter.InsertCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.InsertCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = Global.System.Data.ConnectionState.Closed) Then
                    Me.Adapter.InsertCommand.Connection.Close
                End If
            End Try
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Overridable Function Update( _
                    ByVal CURRENCY_CODE As String,  _
                    ByVal CURRENCY_RATE As Decimal,  _
                    ByVal CURRENCY_VISIBLE As Decimal,  _
                    ByVal CURRENCY_SYMBOL As String,  _
                    ByVal CURRENCY_AD As String,  _
                    ByVal CURRENCY_ADNAME As String,  _
                    ByVal CURRENCY_CSTMP As Date,  _
                    ByVal CURRENCY_LUAD As String,  _
                    ByVal CURRENCY_LUADNAME As String,  _
                    ByVal CURRENCY_LUSTMP As Date,  _
                    ByVal Original_CURRENCY_CODE As String,  _
                    ByVal Original_CURRENCY_RATE As Decimal,  _
                    ByVal Original_CURRENCY_VISIBLE As Decimal,  _
                    ByVal Original_CURRENCY_SYMBOL As String,  _
                    ByVal Original_CURRENCY_AD As String,  _
                    ByVal Original_CURRENCY_ADNAME As String,  _
                    ByVal Original_CURRENCY_CSTMP As Date,  _
                    ByVal Original_CURRENCY_LUAD As String,  _
                    ByVal Original_CURRENCY_LUADNAME As String,  _
                    ByVal Original_CURRENCY_LUSTMP As Date) As Integer
            If (CURRENCY_CODE Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_CODE")
            Else
                Me.Adapter.UpdateCommand.Parameters(0).Value = CType(CURRENCY_CODE,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(1).Value = CType(CURRENCY_RATE,Decimal)
            Me.Adapter.UpdateCommand.Parameters(2).Value = CType(CURRENCY_VISIBLE,Decimal)
            If (CURRENCY_SYMBOL Is Nothing) Then
                Me.Adapter.UpdateCommand.Parameters(3).Value = Global.System.DBNull.Value
            Else
                Me.Adapter.UpdateCommand.Parameters(3).Value = CType(CURRENCY_SYMBOL,String)
            End If
            If (CURRENCY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_AD")
            Else
                Me.Adapter.UpdateCommand.Parameters(4).Value = CType(CURRENCY_AD,String)
            End If
            If (CURRENCY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_ADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(5).Value = CType(CURRENCY_ADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(6).Value = CType(CURRENCY_CSTMP,Date)
            If (CURRENCY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_LUAD")
            Else
                Me.Adapter.UpdateCommand.Parameters(7).Value = CType(CURRENCY_LUAD,String)
            End If
            If (CURRENCY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("CURRENCY_LUADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(8).Value = CType(CURRENCY_LUADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(9).Value = CType(CURRENCY_LUSTMP,Date)
            If (Original_CURRENCY_CODE Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_CODE")
            Else
                Me.Adapter.UpdateCommand.Parameters(10).Value = CType(Original_CURRENCY_CODE,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(11).Value = CType(Original_CURRENCY_RATE,Decimal)
            Me.Adapter.UpdateCommand.Parameters(12).Value = CType(Original_CURRENCY_VISIBLE,Decimal)
            If (Original_CURRENCY_SYMBOL Is Nothing) Then
                Me.Adapter.UpdateCommand.Parameters(13).Value = CType(1,Object)
                Me.Adapter.UpdateCommand.Parameters(14).Value = Global.System.DBNull.Value
            Else
                Me.Adapter.UpdateCommand.Parameters(13).Value = CType(0,Object)
                Me.Adapter.UpdateCommand.Parameters(14).Value = CType(Original_CURRENCY_SYMBOL,String)
            End If
            If (Original_CURRENCY_AD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_AD")
            Else
                Me.Adapter.UpdateCommand.Parameters(15).Value = CType(Original_CURRENCY_AD,String)
            End If
            If (Original_CURRENCY_ADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_ADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(16).Value = CType(Original_CURRENCY_ADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(17).Value = CType(Original_CURRENCY_CSTMP,Date)
            If (Original_CURRENCY_LUAD Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_LUAD")
            Else
                Me.Adapter.UpdateCommand.Parameters(18).Value = CType(Original_CURRENCY_LUAD,String)
            End If
            If (Original_CURRENCY_LUADNAME Is Nothing) Then
                Throw New Global.System.ArgumentNullException("Original_CURRENCY_LUADNAME")
            Else
                Me.Adapter.UpdateCommand.Parameters(19).Value = CType(Original_CURRENCY_LUADNAME,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(20).Value = CType(Original_CURRENCY_LUSTMP,Date)
            Dim previousConnectionState As Global.System.Data.ConnectionState = Me.Adapter.UpdateCommand.Connection.State
            If ((Me.Adapter.UpdateCommand.Connection.State And Global.System.Data.ConnectionState.Open)  _
                        <> Global.System.Data.ConnectionState.Open) Then
                Me.Adapter.UpdateCommand.Connection.Open
            End If
            Try 
                Dim returnValue As Integer = Me.Adapter.UpdateCommand.ExecuteNonQuery
                Return returnValue
            Finally
                If (previousConnectionState = Global.System.Data.ConnectionState.Closed) Then
                    Me.Adapter.UpdateCommand.Connection.Close
                End If
            End Try
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0"),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Overridable Function Update( _
                    ByVal CURRENCY_RATE As Decimal,  _
                    ByVal CURRENCY_VISIBLE As Decimal,  _
                    ByVal CURRENCY_SYMBOL As String,  _
                    ByVal CURRENCY_AD As String,  _
                    ByVal CURRENCY_ADNAME As String,  _
                    ByVal CURRENCY_CSTMP As Date,  _
                    ByVal CURRENCY_LUAD As String,  _
                    ByVal CURRENCY_LUADNAME As String,  _
                    ByVal CURRENCY_LUSTMP As Date,  _
                    ByVal Original_CURRENCY_CODE As String,  _
                    ByVal Original_CURRENCY_RATE As Decimal,  _
                    ByVal Original_CURRENCY_VISIBLE As Decimal,  _
                    ByVal Original_CURRENCY_SYMBOL As String,  _
                    ByVal Original_CURRENCY_AD As String,  _
                    ByVal Original_CURRENCY_ADNAME As String,  _
                    ByVal Original_CURRENCY_CSTMP As Date,  _
                    ByVal Original_CURRENCY_LUAD As String,  _
                    ByVal Original_CURRENCY_LUADNAME As String,  _
                    ByVal Original_CURRENCY_LUSTMP As Date) As Integer
            Return Me.Update(Original_CURRENCY_CODE, CURRENCY_RATE, CURRENCY_VISIBLE, CURRENCY_SYMBOL, CURRENCY_AD, CURRENCY_ADNAME, CURRENCY_CSTMP, CURRENCY_LUAD, CURRENCY_LUADNAME, CURRENCY_LUSTMP, Original_CURRENCY_CODE, Original_CURRENCY_RATE, Original_CURRENCY_VISIBLE, Original_CURRENCY_SYMBOL, Original_CURRENCY_AD, Original_CURRENCY_ADNAME, Original_CURRENCY_CSTMP, Original_CURRENCY_LUAD, Original_CURRENCY_LUADNAME, Original_CURRENCY_LUSTMP)
        End Function
    End Class
End Namespace
